package constants

const (
	MODLOG_RESETPW = iota
	MODLOG_ADMIN_VETO
	MODLOG_ADMIN_MAKE
	// MODLOG_ADMIN_PROPOSE
	// MODLOG_ADMIN_CONFIRM
	MODLOG_REMOVE_USER
	// MODLOG_DELETE_VETO
	// MODLOG_DELETE_PROPOSE
	// MODLOG_DELETE_CONFIRM
)
